version: '3'
services:
  app:
    container_name: app-springboot-postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbpostgresql:5432/customer
    image: app-springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_DB=customer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
